
' title "End Game"

' |User|
' start
' repeat
'     if (End game action?) then (surrender)
'         :Click on surrender button ; 
    
'     else (Propose draw)
'         :Click on Propose draw button;
'         |System|
'         :validify draw request;
'         |User|
'         :Show notification for other player "Player white|black want to draw game" ;  
'         if(Click on draw?) then (yes)
            
'         else (no)
'             :Switch player;
'             while (game is not over)
'         endif  
' repeat while (game is not over) is (true)
' ' :Click on Start Button;
' endif 
' |System|
' :Display game result screen;
' :Enable Screen Game Action;

' |User|
' :Let User Play The Game;

' stop
' @enduml
@startuml "Play a game activity diagram"
title "End Game"

|User|

start
repeat
    if (End game action?) then (surrender)
        |User|
        :Click on surrender button;      
        :Show notification for other player "Player white|black surrender";
        |System|
        :Validate surrender request;
        ' |User|
        ' :Show notification for other player "Player white|black surrender";
    else (Propose draw)
        |User|
        :Click on Propose draw button;
        :Show notification for other player "Player white|black want to draw game";
        |System|
        :Validate draw request;
        ' |User|
        ' :Show notification for other player "Player white|black want to draw game";

        ' if (Click on draw?) then (yes)
        
        ' else (no)
        '     |System|
        '     ' repeat while (game is not over) is (true)
        '     :Switch player;          
    endif   
        repeat while (End game vertify?) is (no)
        ->yes;
' repeat while (game is not over) is (true)
|System|
:Display game result screen;
:End game;
|User|
:Review game result;
stop
@enduml
